[target.wasm32-unknown-emscripten]
rustflags = [
    "-C", "link-args=-sSIDE_MODULE=2",
    "-C", "link-args=-pthread",
    "-C", "target-feature=+atomics,+bulk-memory,+mutable-globals",
    "-C", "llvm-args=-enable-emscripten-cxx-exceptions=0",
    "-Z", "link-native-libraries=no"
]
